# Site settings
title: Minimal Staticman v3 Demo
subtitle: A barebone GitHub Pages with static comments
email: your-email@domain.com
description: Test
baseurl: ""
url: "https://stoic-hoover-77ba7f.netlify.app/"
locale: en
github_username:  pedro006

# Build settings
markdown: kramdown

staticman:
  api: "https://staticman3.herokuapp.com/v3/entry/github/pedro006/teststaticman/master/comments"
  path: "_data/comments"


exclude:
  - .jekyll-cache
  - README.md
  - LICENSE.txt
  - netlify.toml
  - feed.xml
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/